# Generated by Django 2.2 on 2023-07-11 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score_min',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('test', 'тест'), ('interview', 'собеседование'), ('creative_test', 'творческое испытание')], max_length=50, verbose_name='type'),
        ),
    ]
