# Generated by Django 2.2 on 2023-07-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20230711_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.Exam')),
            ],
        ),
    ]
