# Generated by Django 2.2 on 2023-07-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField(verbose_name='file')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.Subject')),
            ],
        ),
    ]
